### ISSUE TITLE
[Pre-commit] Add a configuration file

### ISSUE THREAD

**Issue by mgrzybek** [InseeFrLab/onyxia-api#103]
In order to improve the code quality, we should add some pre-commit tasks, such as linting, `yaml` / `json` cleanup, `java` coding style…

https://pre-commit.com/hooks.html
https://github.com/macisamuele/language-formatters-pre-commit-hooks

**Comment by alexisdondon** [comment]
@olevitt the projet have a spotless:apply configuration could be closed no?

**Comment by olevitt** [comment]
Yes 👍
