### ISSUE TITLE
generate service id conform to marathon specification

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-api#14]
user.getIdep() + "/" + pkg.getName() can generate non conform Id.
Marathon allow only [a-z][0-9]-
We should transform this strings

**Comment by olevitt** [comment]
See https://github.com/InseeFrLab/onyxia-api/blob/master/onyxia-api/src/main/java/fr/insee/onyxia/api/services/control/IDEnforcer.java (which, btw, has wrong documentation as it enforces id's, not reverse proxy urls).  
`/` is also permitted to separate folders. We should make sure to sanitize user.getIdep(), pkg.getName() and, to be safe, the whole string.
