### ISSUE TITLE
remove status ('alpha', 'beta', 'stable' ) 

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-api#15]
We should not classify services into this 3 categories.
We should also remove the marathon label "ONYXIA_STATUS": "" for self services

**Comment by Donatien26** [comment]
maybe close this issue ? @olevitt

**Comment by olevitt** [comment]
This looks mostly like a duplicate of #16   + removing `ONYXIA_STATUS` related code

**Comment by olevitt** [comment]
Fixed by #30
