### ISSUE TITLE
remove endpoint for getting services

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-api#16]
Getting services with marathon labels is not good. 
We should fetch this list on an external json ressource directly with UI

**Comment by olevitt** [comment]
`our-lab` endpoints are not needed anymore and can be safely removed

**Comment by Ragatzino** [comment]
Apparently it's already removed, (can't find our-lab endpoint)

**Comment by olevitt** [comment]
Fixed by #30
