### ISSUE TITLE
[FEATURE REQUEST] Allow application deployment only in group namespace (not in individual namespace)

### ISSUE THREAD

**Issue by Donatien26** [InseeFrLab/onyxia-api#168]
It cool be great to be able to enable or disable the ability to deploy apps/service in individual namespace

**Comment by olevitt** [comment]
Hello,

As far as onyxia-API is concerned, it should probably be as simple as adding a condition to this line : https://github.com/InseeFrLab/onyxia-api/blob/0820d135b7354dba8e2f46a480e24b7f23d12881/onyxia-api/src/main/java/fr/insee/onyxia/api/user/OnyxiaUserProvider.java#L25

But I think some work is needed on onyxia-web to support cases when there is no user project (and also I'm not sure onyxia-web even reads this data from the API)

**Comment by fcomte** [comment]
https://github.com/InseeFrLab/onyxia-api/pull/173
