### ISSUE TITLE
[FEATURE REQUEST] Allow a mode where onyxia create no namespace /bucket of any kind

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/onyxia-api#172]
Allow a mode where onyxia is not the one that :
- create namespace if not exists.
- create bucket if not exists.

**Comment by fcomte** [comment]
I think the mode we must create for onyxia-api is : 
- do not create namespace of any kind.
- do not create bucket of any kind neither.

I think it's much simpler

**Comment by fcomte** [comment]
done : https://github.com/InseeFrLab/onyxia-api/pull/180
