### ISSUE TITLE
[doc] - link to kubernetes client used not working

### ISSUE THREAD

**Issue by patlachance** [InseeFrLab/onyxia-api#197]
In this section [Onyxia API compatibility matrix with Kubernetes](https://github.com/InseeFrLab/onyxia-api/blob/master/README.md#onyxia-api-compatibility-matrix-with-kubernetes), the second link doesn't work.

See [here](https://github.com/fabric8io/kubernetes-client#kubernetes-compatibility-matrix) for the compatibility matrix and ***[[here](https://github.com/InseeFrLab/onyxia-api/blob/6d6272c7ff5f0d0e9a7b2b6fa35d3f57957e39df/onyxia-api/helm-wrapper/pom.xml)***] for the current version used by Onyxia.

**Comment by olevitt** [comment]
Thanks :+1:
