### ISSUE TITLE
Support alternatives to preferred_username

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-api#199]
Onyxia-API at the moment derives the userid (idep) from the `preferred_username` claim of the JWT token.  
This works in most cases but some organisations use special characters in their `preferred_username` which makes Onyxia unusable.  
The UI already supports that (see https://github.com/InseeFrLab/onyxia-web/blob/main/.env#L16).  
We should support this in the API

**Comment by patlachance** [comment]
Thanks a lot!
