### ISSUE TITLE
Add application events

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-api#294]
It could be interesting to have onyxia publish key application events such as service creation, deletion ...
Not sure how those events should be published or which form they should have but first step could be to implement an event system internally and make a simple logger to output them in the logs.  
Something like this https://www.baeldung.com/spring-events should be enough as a first step

**Comment by olevitt** [comment]
Work has begun on #324 but we are not sure what log format we should use for those events and, more generally, for all Onyxia-API logs.  
Some of our options are :    
- Moving everything (all logs including events) to JSON
- Keeping the existing log format (which is spring boot / logback default format) but outputing the events payload as JSON  
-  Switching to another log format that could be easily parsed by log management software. But I can't find any definitive recommended format

Any thoughts / ideas on that ?

**Comment by johnksv** [comment]
I think suggestion 2 (`Keeping the existing log format (which is spring boot / logback default format) but outputing the events payload as JSON` ) makes the most sense. By sticking to the default it we can make use of the spring boot / logback community and all the knowledge which exists. I also think this is the correct approach generally (to log in "plain" format in the code and let the logging framework take care of the format).
My suggestion is to add a logback.xml (and necessary dependencies) and have either a profile or ENV-variable which control if the log is "standard" or JSON.  

One question regarding this issue, if i understand correctly: That the application should publish events which purpose is to be logged? Any other?

Is there to later do some graphing or other on these events? In that case I would recommend (and have been thinking about) exposing some metric. Spring boot comes with out-of-the-box support for https://micrometer.io/ , such that metrics easily can be added and exposed to services like prometheus

**Comment by olevitt** [comment]
Thanks for your input, it makes sense to me :+1: 

The idea currently is to have a system of events / listeners inside the API dispatching events with metadata (service x installed on namespace y by user z / service uninstalled / namespace creation ...) with an initial default listener implementation (enabled or disabled by default, tbd) that would log the events and possibility to add more listeners either for Onyxia-API internal use or for things like implementing webhooks support (see #261 ) sometime in the future.

Graphing will probably stay out of scope of the Onyxia project (unless someone is motivated enough to create a `onyxia-admin` module but it's not planned) and be up to each organization to setup their monitoring and observability. At SSPCloud we are currently planning on parsing those events with our existing fluent-bit installation feeding a loki and we will do graphing and dataviz on grafana.

As for the metrics, I think it's a different usecase. What metric were you thinking about ? At first we thought about adding a service created counter for exemple but I think it's more useful to have whole events with metadata than counters and gauges in this case ?

**Comment by johnksv** [comment]
Make sense 👍🏻 
I do not have any specific ideas regarding metrics, was just interested if that would solve the problem, which you answered.
