### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by johnksv** [InseeFrLab/onyxia-api#319]
**Suggestion:**
Rename the `master` branch to `main`.

**Reasoning:**
- Follow same branch name as https://github.com/InseeFrLab/onyxia
- `main` is the suggested name for the default branch, from github as well as many others.

**Solution:**
Should be done via the renaming default branch name, as documented:  https://github.com/github/renaming?tab=readme-ov-file#renaming-existing-branches

Forks and contributors will be effected.

**Comment by olevitt** [comment]
Agreed, I will take care of that
