### ISSUE TITLE
Use JSON5 (JSON for humans) for parsing configurations.  

### ISSUE THREAD

**Issue by garronej** [InseeFrLab/onyxia-api#334]
Hello,  

I suggest switching from regular JSON to [JSON5](https://json5.org/) for parsing the catalog and region configuration.  
It's much better suited for the usecase.  
It would be great if a trailing coma wouldn't prevent the API to start.  
Also it would be very nice to be able to comment out part of the configuration if needed (Regular JSON does not support comments).  

I use implemented this approach for the onyxia-web configuration already as explained here: https://youtu.be/NrVuVXsbloA?si=Fnu7sEwLuYl-t1uA&t=796

**Comment by garronej** [comment]
Here is a JSON5 Java implementation: https://github.com/marhali/json5-java?tab=readme-ov-file

**Comment by johnksv** [comment]
This could be a nice feature. I belive the built in jackson json parser could be tuned to match this behaviour: https://github.com/FasterXML/jackson-core/wiki/JsonReadFeatures
https://docs.spring.io/spring-boot/docs/3.1.4/reference/htmlsingle/#howto.spring-mvc.customize-jackson-objectmapper

**Comment by johnksv** [comment]
Saw that a custom object mapper was used. I took the liberty to provide a PR

**Comment by garronej** [comment]
Let's go @johnksv, you're the man!

**Comment by johnksv** [comment]
This issue can be closed since it was merged in #344

**Comment by garronej** [comment]
Yes thanks!

**Comment by garronej** [comment]
Note however that, as of today the region and catalog configuration are parsed as YAML in the values as opposed to onyxia-web where the env configuration are parsed as string (YAML is a superset of JSON).  
So to use comment we can just use `#` ans the trailing slashes where already accepted. Sorry for overseeing this :/
