### ISSUE TITLE
Events are not properly retrieved

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-api#381]
Hi !  

Current logic for events retrieval (https://github.com/InseeFrLab/onyxia-api/blob/42060778dc60bfea7e407c5321937a97889ec75b/onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmAppsService.java#L481) is flawed as there is no warranty that the pod name contains the helm release name (e.g : hive-metastore from inseefrlab/helm-charts-databases and many many more).  
This logic should be reworked to be more reliable.  
Once this fix is made, work on displaying it in the UI will be able to begin

**Comment by fcomte** [comment]
@olevitt  work on UI is done :)

**Comment by olevitt** [comment]
Events have been moved to the namespace level in #405 .
I think we should remove the events retrieval that is done at release level
